name: Serenity BDD Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'gradle'
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Run tests
      run: ./gradlew clean test
      
    - name: Generate Serenity reports
      if: always()
      run: ./gradlew aggregate
      
    - name: Upload Serenity reports
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: serenity-reports
        path: target/site/serenity/
        retention-days: 30
        
    - name: Publish test results
      if: always()
      uses: EnricoMi/publish-unit-test-result-action@v2
      with:
        files: |
          build/test-results/**/*.xml
